### ISSUE TITLE
Data plugins?

### ISSUE THREAD

**Issue by YugiFanGX** [ubports/account-plugins#24]
are these still used? https://github.com/ubports/account-plugins/tree/master/data/providers

The data, src, tools and debian folders, seem useless to me. except some graphics in data/icons..

Could not find any option to e.g. add a FB account or use the share option with it

**Comment by dobey** [comment]
Yes these are still "used." However, in order for the account to show up in settings as something you can add, there must be an app installed which is registered to use the account. Without any app using the account type, it is hidden (as there would be no point to adding said account).

**Comment by UniversalSuperBox** [comment]
This question appears to have been answered, so the request may be closed.
