### ISSUE TITLE
Nextcloud plugin is not working

### ISSUE THREAD

**Issue by deepsidhu1313** [ubports/account-plugins#31]
I tried logging into my nextcloud (private instance) account on nexus 7 wifi (flo) which is running 16.04 (ota-5). But it is not working. Screen items gets disabled for few seconds then again gets enabled.

**Comment by UniversalSuperBox** [comment]
This appears to be a duplicate of https://github.com/ubports/ubuntu-touch/issues/1434, which has now been downgraded to https://github.com/ubports/ubuntu-touch/issues/1723
