### ISSUE TITLE
Unable to login with twitter : inifinite loading

### ISSUE THREAD

**Issue by manland** [ubports/account-plugins#41]
*As discussed on [ubports forum](https://forums.ubports.com/topic/4070/what-the-future-of-accounts)*

With this code:

```qml
import Ubuntu.OnlineAccounts.Client 0.1

Button {
    id: btnTwitter
    anchors.centerIn: parent
    text: "Create Twitter account"
    onClicked: setup.exec()
}
Setup {
    id: setup
    applicationId: "touchtwitter"
    providerId: "twitter"
}
```

When I click on the button, webview open but infinite loading.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/account-plugins/-/issues/2
