### ISSUE TITLE
Unable to login with facebook : App in development mode

### ISSUE THREAD

**Issue by manland** [ubports/account-plugins#42]
*As discussed on [ubports forum](https://forums.ubports.com/topic/4070/what-the-future-of-accounts)*

When I try to login with this code:

```qml
import Ubuntu.OnlineAccounts.Client 0.1

Button {
    id: btnFacebook
    anchors.top: btnTwitter.bottom
    text: "Create Facebook account"
    onClicked: setup2.exec()
}
Setup {
    id: setup2
    applicationId: "touchtwitter"
    providerId: "facebook"
}
```
Webview open and facebook login appear. But at end of process I have a facebook error `this application is in development mode` and I can't finish the login.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/account-plugins/-/issues/1
