### ISSUE TITLE
Password character :

### ISSUE THREAD

**Issue by ernesst** [ubports/account-plugins#8]
If using : in my password I cannot log in.
Removing the : in the password does the trick. 

Not urgent, but to keep in mind to advise users... in order to avoid frustration.

**Comment by jonnius** [comment]
Do you mean nextcloud? This is a duplicate of ubports/ubuntu-touch#468.

**Comment by ernesst** [comment]
Yes it's related.

**Comment by Flohack74** [comment]
Resolved by https://github.com/ubports/account-plugins/pull/16
